spring.application.name=safeflight
logging.file.name=logs/safeflight.log
logging.level.org.apache.catalina=INFO
logging.level.org.apache.tomcat=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO
logging.level.org.apache.coyote=INFO
logging.level.org.apache.catalina.core=INFO

